FROM docker-daemon:docker.io/openjdk:11.0.11

ARG TIMEZONE="America/Chicago"
ENV TIMEZONE ${TIMEZONE}
ARG APP="raspi-finance-endpoint"
ENV APP ${APP}
ARG USERNAME="henninb"
ENV USERNAME ${USERNAME}
RUN useradd -M ${USERNAME}

RUN cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
RUN mkdir -p -m 0755 /opt/${APP}/bin
RUN mkdir -p -m 0755 /opt/${APP}/logs/archive
RUN mkdir -p -m 0755 /opt/${APP}/ssl
RUN mkdir -p -m 0755 /opt/${APP}/excel_in
RUN mkdir -p -m 0755 /opt/${APP}/json_in
COPY ./ssl /opt/${APP}/ssl
ADD ./build/libs/${APP}*.jar /opt/${APP}/bin/${APP}.jar
RUN chown -R ${USERNAME}:${USERNAME} /opt/${APP}/*

WORKDIR /opt/${APP}/bin
USER ${USERNAME}

#default on the mac was 522m
CMD java -Duser.timezone=${TIMEZONE} -Xmx2048m -jar /opt/${APP}/bin/${APP}.jar
