services:
  raspi-finance-endpoint:
    env_file:
      - ${ENV_FILE:-env.prod}
    extra_hosts:
      - "postgresql-server:host-gateway"

networks:
  default:
    name: finance-lan
    external: true
