services:
  nginx-reverse-proxy-finance:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    hostname: nginx-reverse-proxy-finance
    container_name: nginx-reverse-proxy-finance
    restart: unless-stopped
    ports:
      - "127.0.0.1:9443:443"  # Security: Bind to localhost only
    # Security: Mount SSL certificates as secrets instead of copying into image
    volumes:
      - ./ssl:/etc/nginx/certs:ro
    # Security: Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    # Security: Enhanced security context
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=50m
      - /var/log/nginx:noexec,nosuid,size=50m
      - /tmp:noexec,nosuid,size=50m
    user: "1001:1001"
