-- Medical Expense Table Creation for Oracle Test Environment
-- Links medical expenses to existing transactions with 1:1 relationship
-- Supports comprehensive medical expense tracking with family member support

CREATE TABLE t_medical_expense (
    medical_expense_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id              NUMBER NOT NULL,
    provider_id                 NUMBER,
    family_member_id            NUMBER,

    -- Core medical expense data
    service_date                DATE NOT NULL,
    service_description         VARCHAR2(500),
    procedure_code              VARCHAR2(20), -- CPT/HCPCS codes
    diagnosis_code              VARCHAR2(20), -- ICD-10 codes

    -- Financial breakdown
    billed_amount              NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    insurance_discount         NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    insurance_paid             NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    patient_responsibility     NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    paid_date                  DATE,

    -- Insurance details
    is_out_of_network          NUMBER(1) DEFAULT 0 NOT NULL,
    claim_number               VARCHAR2(50),
    claim_status               VARCHAR2(20) DEFAULT 'submitted' NOT NULL,

    -- Audit fields
    active_status              NUMBER(1) DEFAULT 1 NOT NULL,
    date_added                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_updated               TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- Constraints
    CONSTRAINT fk_medical_expense_transaction FOREIGN KEY (transaction_id)
        REFERENCES t_transaction(transaction_id) ON DELETE CASCADE,
    CONSTRAINT fk_medical_expense_provider FOREIGN KEY (provider_id)
        REFERENCES t_medical_provider(provider_id),
    CONSTRAINT fk_medical_expense_family_member FOREIGN KEY (family_member_id)
        REFERENCES t_family_member(family_member_id),
    CONSTRAINT uk_medical_expense_transaction UNIQUE (transaction_id),
    CONSTRAINT ck_medical_expense_claim_status CHECK (claim_status IN (
        'submitted', 'processing', 'approved', 'denied', 'paid', 'closed'
    )),
    CONSTRAINT ck_medical_expense_financial_amounts CHECK (
        billed_amount >= 0 AND
        insurance_discount >= 0 AND
        insurance_paid >= 0 AND
        patient_responsibility >= 0
    ),
    CONSTRAINT ck_medical_expense_service_date_valid CHECK (service_date <= CURRENT_DATE),
    CONSTRAINT ck_medical_expense_financial_consistency CHECK (
        billed_amount >= (insurance_discount + insurance_paid + patient_responsibility)
    ),
    CONSTRAINT ck_medical_expense_boolean_network CHECK (is_out_of_network IN (0, 1)),
    CONSTRAINT ck_medical_expense_boolean_active CHECK (active_status IN (0, 1))
);

-- Performance indexes
CREATE UNIQUE INDEX idx_medical_expense_transaction ON t_medical_expense(transaction_id);
CREATE INDEX idx_medical_expense_provider ON t_medical_expense(provider_id);
CREATE INDEX idx_medical_expense_family_member ON t_medical_expense(family_member_id);
CREATE INDEX idx_medical_expense_service_date ON t_medical_expense(service_date);
CREATE INDEX idx_medical_expense_claim_number ON t_medical_expense(claim_number);
CREATE INDEX idx_medical_expense_claim_status ON t_medical_expense(claim_status);
CREATE INDEX idx_medical_expense_active ON t_medical_expense(active_status, service_date);