--TRUNCATE flyway_schema_history cascade;
TRUNCATE t_category cascade;
TRUNCATE t_description cascade;
TRUNCATE t_parm cascade;
TRUNCATE t_payment cascade;
TRUNCATE t_transaction cascade;
TRUNCATE t_transaction_categories cascade;
TRUNCATE t_receipt_image cascade;
TRUNCATE t_account cascade;