-- Migration: V11__create-token-blacklist.sql
-- Purpose: Persistent JWT token blacklist to survive server restarts
-- Stores SHA-256 hashes of revoked tokens (never raw tokens)

DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists
    FROM user_tables
    WHERE table_name = 'T_TOKEN_BLACKLIST';

    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE t_token_blacklist (
                token_blacklist_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                token_hash         VARCHAR2(64)  NOT NULL,
                expires_at         TIMESTAMP WITH TIME ZONE NOT NULL,
                CONSTRAINT uk_token_blacklist_hash UNIQUE (token_hash)
            )';

        EXECUTE IMMEDIATE 'CREATE INDEX idx_token_bl_expires_at ON t_token_blacklist (expires_at)';
    END IF;
END;
/
