name: Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: dc-${{ github.ref }}
  cancel-in-progress: false

jobs:
  owasp-dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'gradle.properties', 'gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Dependency-Check DB
        uses: actions/cache@v4
        with:
          path: ./.dc-data
          key: ${{ runner.os }}-dcdb-${{ hashFiles('gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-dcdb-

      - name: Run Dependency-Check
        run: ./gradlew dependencyCheckAnalyze -PdependencyCheck.skip=false --info

      - name: Upload Dependency-Check Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          if-no-files-found: warn
          path: |
            build/reports/dependency-check-report.html
            build/reports/dependency-check-report.json
            build/reports/dependency-check/dependency-check-report.html
            build/reports/dependency-check/dependency-check-report.json

